<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\User;
use App\Models\Category;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // Get all approved sellers
        $sellers = User::whereHas('roles', function ($query) {
            $query->where('name', 'seller');
        })->where('is_approved', true)->get();

        $books = [
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'category' => 'Fiction',
                'description' => 'A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.',
                'price' => 12.99,
                'stock' => 25,
                'publication_year' => 1925,
                'publisher' => 'Scribner',
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'category' => 'Fiction',
                'description' => 'A powerful story of racial injustice and childhood innocence in the American South.',
                'price' => 14.99,
                'stock' => 30,
                'publication_year' => 1960,
                'publisher' => 'Harper Perennial',
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'category' => 'Fantasy',
                'description' => 'A dystopian novel depicting a totalitarian society under constant surveillance.',
                'price' => 13.99,
                'stock' => 20,
                'publication_year' => 1949,
                'publisher' => 'Signet Classic',
            ],
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'category' => 'Fantasy',
                'description' => 'The first book in the magical Harry Potter series following a young wizard\'s adventures.',
                'price' => 16.99,
                'stock' => 50,
                'publication_year' => 1997,
                'publisher' => 'Bloomsbury',
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'category' => 'Fantasy',
                'description' => 'A fantasy adventure following Bilbo Baggins on his journey to reclaim treasure from a dragon.',
                'price' => 15.99,
                'stock' => 35,
                'publication_year' => 1937,
                'publisher' => 'Houghton Mifflin',
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'category' => 'Romance',
                'description' => 'A romantic novel of manners exploring love, marriage, and social class in Regency England.',
                'price' => 11.99,
                'stock' => 28,
                'publication_year' => 1913,
                'publisher' => 'Penguin Classics',
            ],
            [
                'title' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'category' => 'Mystery',
                'description' => 'A thriller following symbologist Robert Langdon solving a murder mystery at the Louvre.',
                'price' => 14.99,
                'stock' => 22,
                'publication_year' => 2003,
                'publisher' => 'Doubleday',
            ],
            [
                'title' => 'The Girl with the Dragon Tattoo',
                'author' => 'Stieg Larsson',
                'category' => 'Mystery',
                'description' => 'A gripping mystery involving a journalist and a hacker investigating a decades-old disappearance.',
                'price' => 13.99,
                'stock' => 18,
                'publication_year' => 2005,
                'publisher' => 'Vintage Crime',
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'category' => 'History',
                'description' => 'An exploration of human history from the Stone Age to the modern age.',
                'price' => 18.99,
                'stock' => 40,
                'publication_year' => 2011,
                'publisher' => 'Harper',
            ],
            [
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'category' => 'Non-Fiction',
                'description' => 'A memoir about a woman who grows up in a strict and abusive household but eventually escapes to learn.',
                'price' => 16.99,
                'stock' => 32,
                'publication_year' => 2018,
                'publisher' => 'Random House',
            ],
            [
                'title' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'category' => 'Non-Fiction',
                'description' => 'The authorized biography of Apple co-founder Steve Jobs.',
                'price' => 19.99,
                'stock' => 26,
                'publication_year' => 2011,
                'publisher' => 'Simon & Schuster',
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'category' => 'Self-Help',
                'description' => 'A practical guide to building good habits and breaking bad ones.',
                'price' => 17.99,
                'stock' => 45,
                'publication_year' => 2018,
                'publisher' => 'Avery',
            ],
            [
                'title' => 'The 7 Habits of Highly Effective People',
                'author' => 'Stephen R. Covey',
                'category' => 'Self-Help',
                'description' => 'A self-improvement book providing principles for personal and professional effectiveness.',
                'price' => 15.99,
                'stock' => 38,
                'publication_year' => 1989,
                'publisher' => 'Free Press',
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'category' => 'Science & Technology',
                'description' => 'An exploration of the two systems that drive the way we think and make decisions.',
                'price' => 18.99,
                'stock' => 29,
                'publication_year' => 2011,
                'publisher' => 'Farrar, Straus and Giroux',
            ],
            [
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'category' => 'Science & Technology',
                'description' => 'A landmark volume in science writing exploring cosmology and the universe.',
                'price' => 16.99,
                'stock' => 24,
                'publication_year' => 1988,
                'publisher' => 'Bantam',
            ],
            [
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'category' => 'Business & Economics',
                'description' => 'A guide for entrepreneurs on building successful startups through innovation.',
                'price' => 19.99,
                'stock' => 33,
                'publication_year' => 2011,
                'publisher' => 'Crown Business',
            ],
            [
                'title' => 'Good to Great',
                'author' => 'Jim Collins',
                'category' => 'Business & Economics',
                'description' => 'A study of how companies transition from being good to becoming great.',
                'price' => 18.99,
                'stock' => 27,
                'publication_year' => 2001,
                'publisher' => 'HarperBusiness',
            ],
            [
                'title' => 'Where the Wild Things Are',
                'author' => 'Maurice Sendak',
                'category' => 'Children',
                'description' => 'A children\'s picture book about a boy named Max who sails to an island of wild creatures.',
                'price' => 9.99,
                'stock' => 42,
                'publication_year' => 1963,
                'publisher' => 'Harper Collins',
            ],
            [
                'title' => 'The Very Hungry Caterpillar',
                'author' => 'Eric Carle',
                'category' => 'Children',
                'description' => 'A beloved children\'s book about a caterpillar eating through various foods before becoming a butterfly.',
                'price' => 8.99,
                'stock' => 55,
                'publication_year' => 1969,
                'publisher' => 'Philomel Books',
            ],
            [
                'title' => 'The Fault in Our Stars',
                'author' => 'John Green',
                'category' => 'Young Adult',
                'description' => 'A touching story of two teenagers with cancer who fall in love.',
                'price' => 12.99,
                'stock' => 36,
                'publication_year' => 2012,
                'publisher' => 'Dutton Books',
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'category' => 'Young Adult',
                'description' => 'A dystopian novel about a televised fight to the death in a post-apocalyptic world.',
                'price' => 13.99,
                'stock' => 44,
                'publication_year' => 2008,
                'publisher' => 'Scholastic Press',
            ],
            [
                'title' => 'The Sun and Her Flowers',
                'author' => 'Rupi Kaur',
                'category' => 'Poetry',
                'description' => 'A collection of poetry exploring themes of growth, healing, and self-love.',
                'price' => 14.99,
                'stock' => 31,
                'publication_year' => 2017,
                'publisher' => 'Andrews McMeel',
            ],
            [
                'title' => 'Milk and Honey',
                'author' => 'Rupi Kaur',
                'category' => 'Poetry',
                'description' => 'A poetry collection dealing with survival, femininity, love, and trauma.',
                'price' => 13.99,
                'stock' => 34,
                'publication_year' => 2014,
                'publisher' => 'Andrews McMeel',
            ],
            [
                'title' => 'The Art Book',
                'author' => 'Phaidon Press',
                'category' => 'Arts',
                'description' => 'A comprehensive guide to 600 of the world\'s greatest paintings and sculptures.',
                'price' => 29.99,
                'stock' => 15,
                'publication_year' => 1994,
                'publisher' => 'Phaidon Press',
            ],
            [
                'title' => 'National Geographic: The Photographs',
                'author' => 'National Geographic',
                'category' => 'Arts',
                'description' => 'A stunning collection of the best photography from National Geographic.',
                'price' => 35.99,
                'stock' => 12,
                'publication_year' => 2014,
                'publisher' => 'National Geographic',
            ],
            [
                'title' => 'Salt, Fat, Acid, Heat',
                'author' => 'Samin Nosrat',
                'category' => 'Cooking',
                'description' => 'A masterclass in cooking explaining the four elements of good cooking.',
                'price' => 24.99,
                'stock' => 28,
                'publication_year' => 2017,
                'publisher' => 'Simon & Schuster',
            ],
            [
                'title' => 'The Joy of Cooking',
                'author' => 'Irma S. Rombauer',
                'category' => 'Cooking',
                'description' => 'The classic American cookbook with thousands of recipes and techniques.',
                'price' => 27.99,
                'stock' => 20,
                'publication_year' => 1931,
                'publisher' => 'Scribner',
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'category' => 'Fiction',
                'description' => 'A philosophical novel about a shepherd\'s journey to fulfill his personal legend.',
                'price' => 14.99,
                'stock' => 39,
                'publication_year' => 1988,
                'publisher' => 'HarperOne',
            ],
            [
                'title' => 'Becoming',
                'author' => 'Michelle Obama',
                'category' => 'Non-Fiction',
                'description' => 'The memoir of former First Lady Michelle Obama chronicling her life.',
                'price' => 21.99,
                'stock' => 37,
                'publication_year' => 2018,
                'publisher' => 'Crown',
            ],
            [
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'category' => 'Fantasy',
                'description' => 'A science fiction epic set on the desert planet Arrakis.',
                'price' => 17.99,
                'stock' => 30,
                'publication_year' => 1965,
                'publisher' => 'Ace Books',
            ],
        ];

        foreach ($books as $book) {
            $category = Category::where('name', $book['category'])->first() ?? Category::where('name', 'Others')->first();
            
            $newBook = new Book([
                'seller_id' => $sellers->random()->id,
                'category_id' => $category->id,
                'title' => $book['title'],
                'author' => $book['author'],
                'description' => $book['description'],
                'price' => $book['price'],
                'stock' => $book['stock'],
                'publication_year' => $book['publication_year'],
                'publisher' => $book['publisher'],
            ]);
            
            // Ensure slug is generated during seeding
            $newBook->generateSlug();
            $newBook->save();
        }
    }
}
